#!/bin/sh
name () {
	echo $1 | sed 's/\/\+/\//g' | sed 's:^.*/\([^/]*\)/doc/\(.*\).R$:\1-\2:'|sed 's:/:-:g'
}

if [ "$1" = "-" -o -z "$1" ] ; then
	while read i ; do
		name $i
	done
else
	while [ $1 ] ; do
		name $1
		shift
	done
fi
